// GENERATED CODE -- DO NOT EDIT!

// package: rpcpb
// file: rpcpb/services.proto

import * as rpcpb_services_pb from "../rpcpb/services_pb";
import * as commonpb_common_pb from "../commonpb/common_pb";
import * as sliverpb_sliver_pb from "../sliverpb/sliver_pb";
import * as clientpb_client_pb from "../clientpb/client_pb";
import * as grpc from "@grpc/grpc-js";

interface ISliverRPCService extends grpc.ServiceDefinition<grpc.UntypedServiceImplementation> {
  getVersion: grpc.MethodDefinition<commonpb_common_pb.Empty, clientpb_client_pb.Version>;
  getOperators: grpc.MethodDefinition<commonpb_common_pb.Empty, clientpb_client_pb.Operators>;
  getSessions: grpc.MethodDefinition<commonpb_common_pb.Empty, clientpb_client_pb.Sessions>;
  killSession: grpc.MethodDefinition<sliverpb_sliver_pb.KillSessionReq, commonpb_common_pb.Empty>;
  updateSession: grpc.MethodDefinition<clientpb_client_pb.UpdateSession, clientpb_client_pb.Session>;
  monitorStart: grpc.MethodDefinition<commonpb_common_pb.Empty, commonpb_common_pb.Response>;
  monitorStop: grpc.MethodDefinition<commonpb_common_pb.Empty, commonpb_common_pb.Empty>;
  getJobs: grpc.MethodDefinition<commonpb_common_pb.Empty, clientpb_client_pb.Jobs>;
  killJob: grpc.MethodDefinition<clientpb_client_pb.KillJobReq, clientpb_client_pb.KillJob>;
  startMTLSListener: grpc.MethodDefinition<clientpb_client_pb.MTLSListenerReq, clientpb_client_pb.MTLSListener>;
  startWGListener: grpc.MethodDefinition<clientpb_client_pb.WGListenerReq, clientpb_client_pb.WGListener>;
  startDNSListener: grpc.MethodDefinition<clientpb_client_pb.DNSListenerReq, clientpb_client_pb.DNSListener>;
  startHTTPSListener: grpc.MethodDefinition<clientpb_client_pb.HTTPListenerReq, clientpb_client_pb.HTTPListener>;
  startHTTPListener: grpc.MethodDefinition<clientpb_client_pb.HTTPListenerReq, clientpb_client_pb.HTTPListener>;
  startTCPStagerListener: grpc.MethodDefinition<clientpb_client_pb.StagerListenerReq, clientpb_client_pb.StagerListener>;
  startHTTPStagerListener: grpc.MethodDefinition<clientpb_client_pb.StagerListenerReq, clientpb_client_pb.StagerListener>;
  lootAdd: grpc.MethodDefinition<clientpb_client_pb.Loot, clientpb_client_pb.Loot>;
  lootRm: grpc.MethodDefinition<clientpb_client_pb.Loot, commonpb_common_pb.Empty>;
  lootUpdate: grpc.MethodDefinition<clientpb_client_pb.Loot, clientpb_client_pb.Loot>;
  lootContent: grpc.MethodDefinition<clientpb_client_pb.Loot, clientpb_client_pb.Loot>;
  lootAll: grpc.MethodDefinition<commonpb_common_pb.Empty, clientpb_client_pb.AllLoot>;
  lootAllOf: grpc.MethodDefinition<clientpb_client_pb.Loot, clientpb_client_pb.AllLoot>;
  generate: grpc.MethodDefinition<clientpb_client_pb.GenerateReq, clientpb_client_pb.Generate>;
  regenerate: grpc.MethodDefinition<clientpb_client_pb.RegenerateReq, clientpb_client_pb.Generate>;
  implantBuilds: grpc.MethodDefinition<commonpb_common_pb.Empty, clientpb_client_pb.ImplantBuilds>;
  deleteImplantBuild: grpc.MethodDefinition<clientpb_client_pb.DeleteReq, commonpb_common_pb.Empty>;
  canaries: grpc.MethodDefinition<commonpb_common_pb.Empty, clientpb_client_pb.Canaries>;
  generateWGClientConfig: grpc.MethodDefinition<commonpb_common_pb.Empty, clientpb_client_pb.WGClientConfig>;
  generateUniqueIP: grpc.MethodDefinition<commonpb_common_pb.Empty, clientpb_client_pb.UniqueWGIP>;
  implantProfiles: grpc.MethodDefinition<commonpb_common_pb.Empty, clientpb_client_pb.ImplantProfiles>;
  deleteImplantProfile: grpc.MethodDefinition<clientpb_client_pb.DeleteReq, commonpb_common_pb.Empty>;
  saveImplantProfile: grpc.MethodDefinition<clientpb_client_pb.ImplantProfile, clientpb_client_pb.ImplantProfile>;
  msfStage: grpc.MethodDefinition<clientpb_client_pb.MsfStagerReq, clientpb_client_pb.MsfStager>;
  shellcodeRDI: grpc.MethodDefinition<clientpb_client_pb.ShellcodeRDIReq, clientpb_client_pb.ShellcodeRDI>;
  getCompiler: grpc.MethodDefinition<commonpb_common_pb.Empty, clientpb_client_pb.Compiler>;
  websites: grpc.MethodDefinition<commonpb_common_pb.Empty, clientpb_client_pb.Websites>;
  website: grpc.MethodDefinition<clientpb_client_pb.Website, clientpb_client_pb.Website>;
  websiteRemove: grpc.MethodDefinition<clientpb_client_pb.Website, commonpb_common_pb.Empty>;
  websiteAddContent: grpc.MethodDefinition<clientpb_client_pb.WebsiteAddContent, clientpb_client_pb.Website>;
  websiteUpdateContent: grpc.MethodDefinition<clientpb_client_pb.WebsiteAddContent, clientpb_client_pb.Website>;
  websiteRemoveContent: grpc.MethodDefinition<clientpb_client_pb.WebsiteRemoveContent, clientpb_client_pb.Website>;
  ping: grpc.MethodDefinition<sliverpb_sliver_pb.Ping, sliverpb_sliver_pb.Ping>;
  ps: grpc.MethodDefinition<sliverpb_sliver_pb.PsReq, sliverpb_sliver_pb.Ps>;
  terminate: grpc.MethodDefinition<sliverpb_sliver_pb.TerminateReq, sliverpb_sliver_pb.Terminate>;
  ifconfig: grpc.MethodDefinition<sliverpb_sliver_pb.IfconfigReq, sliverpb_sliver_pb.Ifconfig>;
  netstat: grpc.MethodDefinition<sliverpb_sliver_pb.NetstatReq, sliverpb_sliver_pb.Netstat>;
  ls: grpc.MethodDefinition<sliverpb_sliver_pb.LsReq, sliverpb_sliver_pb.Ls>;
  cd: grpc.MethodDefinition<sliverpb_sliver_pb.CdReq, sliverpb_sliver_pb.Pwd>;
  pwd: grpc.MethodDefinition<sliverpb_sliver_pb.PwdReq, sliverpb_sliver_pb.Pwd>;
  rm: grpc.MethodDefinition<sliverpb_sliver_pb.RmReq, sliverpb_sliver_pb.Rm>;
  mkdir: grpc.MethodDefinition<sliverpb_sliver_pb.MkdirReq, sliverpb_sliver_pb.Mkdir>;
  download: grpc.MethodDefinition<sliverpb_sliver_pb.DownloadReq, sliverpb_sliver_pb.Download>;
  upload: grpc.MethodDefinition<sliverpb_sliver_pb.UploadReq, sliverpb_sliver_pb.Upload>;
  processDump: grpc.MethodDefinition<sliverpb_sliver_pb.ProcessDumpReq, sliverpb_sliver_pb.ProcessDump>;
  runAs: grpc.MethodDefinition<sliverpb_sliver_pb.RunAsReq, sliverpb_sliver_pb.RunAs>;
  impersonate: grpc.MethodDefinition<sliverpb_sliver_pb.ImpersonateReq, sliverpb_sliver_pb.Impersonate>;
  revToSelf: grpc.MethodDefinition<sliverpb_sliver_pb.RevToSelfReq, sliverpb_sliver_pb.RevToSelf>;
  getSystem: grpc.MethodDefinition<clientpb_client_pb.GetSystemReq, sliverpb_sliver_pb.GetSystem>;
  task: grpc.MethodDefinition<sliverpb_sliver_pb.TaskReq, sliverpb_sliver_pb.Task>;
  msf: grpc.MethodDefinition<clientpb_client_pb.MSFReq, commonpb_common_pb.Empty>;
  msfRemote: grpc.MethodDefinition<clientpb_client_pb.MSFRemoteReq, commonpb_common_pb.Empty>;
  executeAssembly: grpc.MethodDefinition<sliverpb_sliver_pb.ExecuteAssemblyReq, sliverpb_sliver_pb.ExecuteAssembly>;
  migrate: grpc.MethodDefinition<clientpb_client_pb.MigrateReq, sliverpb_sliver_pb.Migrate>;
  execute: grpc.MethodDefinition<sliverpb_sliver_pb.ExecuteReq, sliverpb_sliver_pb.Execute>;
  executeToken: grpc.MethodDefinition<sliverpb_sliver_pb.ExecuteTokenReq, sliverpb_sliver_pb.Execute>;
  sideload: grpc.MethodDefinition<sliverpb_sliver_pb.SideloadReq, sliverpb_sliver_pb.Sideload>;
  spawnDll: grpc.MethodDefinition<sliverpb_sliver_pb.InvokeSpawnDllReq, sliverpb_sliver_pb.SpawnDll>;
  screenshot: grpc.MethodDefinition<sliverpb_sliver_pb.ScreenshotReq, sliverpb_sliver_pb.Screenshot>;
  namedPipes: grpc.MethodDefinition<sliverpb_sliver_pb.NamedPipesReq, sliverpb_sliver_pb.NamedPipes>;
  tCPListener: grpc.MethodDefinition<sliverpb_sliver_pb.TCPPivotReq, sliverpb_sliver_pb.TCPPivot>;
  listPivots: grpc.MethodDefinition<sliverpb_sliver_pb.PivotListReq, sliverpb_sliver_pb.PivotList>;
  startService: grpc.MethodDefinition<sliverpb_sliver_pb.StartServiceReq, sliverpb_sliver_pb.ServiceInfo>;
  stopService: grpc.MethodDefinition<sliverpb_sliver_pb.StopServiceReq, sliverpb_sliver_pb.ServiceInfo>;
  removeService: grpc.MethodDefinition<sliverpb_sliver_pb.RemoveServiceReq, sliverpb_sliver_pb.ServiceInfo>;
  makeToken: grpc.MethodDefinition<sliverpb_sliver_pb.MakeTokenReq, sliverpb_sliver_pb.MakeToken>;
  getEnv: grpc.MethodDefinition<sliverpb_sliver_pb.EnvReq, sliverpb_sliver_pb.EnvInfo>;
  setEnv: grpc.MethodDefinition<sliverpb_sliver_pb.SetEnvReq, sliverpb_sliver_pb.SetEnv>;
  unsetEnv: grpc.MethodDefinition<sliverpb_sliver_pb.UnsetEnvReq, sliverpb_sliver_pb.UnsetEnv>;
  backdoor: grpc.MethodDefinition<sliverpb_sliver_pb.BackdoorReq, sliverpb_sliver_pb.Backdoor>;
  registryRead: grpc.MethodDefinition<sliverpb_sliver_pb.RegistryReadReq, sliverpb_sliver_pb.RegistryRead>;
  registryWrite: grpc.MethodDefinition<sliverpb_sliver_pb.RegistryWriteReq, sliverpb_sliver_pb.RegistryWrite>;
  registryCreateKey: grpc.MethodDefinition<sliverpb_sliver_pb.RegistryCreateKeyReq, sliverpb_sliver_pb.RegistryCreateKey>;
  runSSHCommand: grpc.MethodDefinition<sliverpb_sliver_pb.SSHCommandReq, sliverpb_sliver_pb.SSHCommand>;
  wGStartPortForward: grpc.MethodDefinition<sliverpb_sliver_pb.WGPortForwardStartReq, sliverpb_sliver_pb.WGPortForward>;
  wGStopPortForward: grpc.MethodDefinition<sliverpb_sliver_pb.WGPortForwardStopReq, sliverpb_sliver_pb.WGPortForward>;
  wGStartSocks: grpc.MethodDefinition<sliverpb_sliver_pb.WGSocksStartReq, sliverpb_sliver_pb.WGSocks>;
  wGStopSocks: grpc.MethodDefinition<sliverpb_sliver_pb.WGSocksStopReq, sliverpb_sliver_pb.WGSocks>;
  wGListForwarders: grpc.MethodDefinition<sliverpb_sliver_pb.WGTCPForwardersReq, sliverpb_sliver_pb.WGTCPForwarders>;
  wGListSocksServers: grpc.MethodDefinition<sliverpb_sliver_pb.WGSocksServersReq, sliverpb_sliver_pb.WGSocksServers>;
  shell: grpc.MethodDefinition<sliverpb_sliver_pb.ShellReq, sliverpb_sliver_pb.Shell>;
  portfwd: grpc.MethodDefinition<sliverpb_sliver_pb.PortfwdReq, sliverpb_sliver_pb.Portfwd>;
  createTunnel: grpc.MethodDefinition<sliverpb_sliver_pb.Tunnel, sliverpb_sliver_pb.Tunnel>;
  closeTunnel: grpc.MethodDefinition<sliverpb_sliver_pb.Tunnel, commonpb_common_pb.Empty>;
  tunnelData: grpc.MethodDefinition<sliverpb_sliver_pb.TunnelData, sliverpb_sliver_pb.TunnelData>;
  events: grpc.MethodDefinition<commonpb_common_pb.Empty, clientpb_client_pb.Event>;
}

export const SliverRPCService: ISliverRPCService;

export class SliverRPCClient extends grpc.Client {
  constructor(address: string, credentials: grpc.ChannelCredentials, options?: object);
  getVersion(argument: commonpb_common_pb.Empty, callback: grpc.requestCallback<clientpb_client_pb.Version>): grpc.ClientUnaryCall;
  getVersion(argument: commonpb_common_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Version>): grpc.ClientUnaryCall;
  getVersion(argument: commonpb_common_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Version>): grpc.ClientUnaryCall;
  getOperators(argument: commonpb_common_pb.Empty, callback: grpc.requestCallback<clientpb_client_pb.Operators>): grpc.ClientUnaryCall;
  getOperators(argument: commonpb_common_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Operators>): grpc.ClientUnaryCall;
  getOperators(argument: commonpb_common_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Operators>): grpc.ClientUnaryCall;
  getSessions(argument: commonpb_common_pb.Empty, callback: grpc.requestCallback<clientpb_client_pb.Sessions>): grpc.ClientUnaryCall;
  getSessions(argument: commonpb_common_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Sessions>): grpc.ClientUnaryCall;
  getSessions(argument: commonpb_common_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Sessions>): grpc.ClientUnaryCall;
  killSession(argument: sliverpb_sliver_pb.KillSessionReq, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  killSession(argument: sliverpb_sliver_pb.KillSessionReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  killSession(argument: sliverpb_sliver_pb.KillSessionReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  updateSession(argument: clientpb_client_pb.UpdateSession, callback: grpc.requestCallback<clientpb_client_pb.Session>): grpc.ClientUnaryCall;
  updateSession(argument: clientpb_client_pb.UpdateSession, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Session>): grpc.ClientUnaryCall;
  updateSession(argument: clientpb_client_pb.UpdateSession, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Session>): grpc.ClientUnaryCall;
  monitorStart(argument: commonpb_common_pb.Empty, callback: grpc.requestCallback<commonpb_common_pb.Response>): grpc.ClientUnaryCall;
  monitorStart(argument: commonpb_common_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<commonpb_common_pb.Response>): grpc.ClientUnaryCall;
  monitorStart(argument: commonpb_common_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<commonpb_common_pb.Response>): grpc.ClientUnaryCall;
  monitorStop(argument: commonpb_common_pb.Empty, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  monitorStop(argument: commonpb_common_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  monitorStop(argument: commonpb_common_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  getJobs(argument: commonpb_common_pb.Empty, callback: grpc.requestCallback<clientpb_client_pb.Jobs>): grpc.ClientUnaryCall;
  getJobs(argument: commonpb_common_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Jobs>): grpc.ClientUnaryCall;
  getJobs(argument: commonpb_common_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Jobs>): grpc.ClientUnaryCall;
  killJob(argument: clientpb_client_pb.KillJobReq, callback: grpc.requestCallback<clientpb_client_pb.KillJob>): grpc.ClientUnaryCall;
  killJob(argument: clientpb_client_pb.KillJobReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.KillJob>): grpc.ClientUnaryCall;
  killJob(argument: clientpb_client_pb.KillJobReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.KillJob>): grpc.ClientUnaryCall;
  startMTLSListener(argument: clientpb_client_pb.MTLSListenerReq, callback: grpc.requestCallback<clientpb_client_pb.MTLSListener>): grpc.ClientUnaryCall;
  startMTLSListener(argument: clientpb_client_pb.MTLSListenerReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.MTLSListener>): grpc.ClientUnaryCall;
  startMTLSListener(argument: clientpb_client_pb.MTLSListenerReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.MTLSListener>): grpc.ClientUnaryCall;
  startWGListener(argument: clientpb_client_pb.WGListenerReq, callback: grpc.requestCallback<clientpb_client_pb.WGListener>): grpc.ClientUnaryCall;
  startWGListener(argument: clientpb_client_pb.WGListenerReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.WGListener>): grpc.ClientUnaryCall;
  startWGListener(argument: clientpb_client_pb.WGListenerReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.WGListener>): grpc.ClientUnaryCall;
  startDNSListener(argument: clientpb_client_pb.DNSListenerReq, callback: grpc.requestCallback<clientpb_client_pb.DNSListener>): grpc.ClientUnaryCall;
  startDNSListener(argument: clientpb_client_pb.DNSListenerReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.DNSListener>): grpc.ClientUnaryCall;
  startDNSListener(argument: clientpb_client_pb.DNSListenerReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.DNSListener>): grpc.ClientUnaryCall;
  startHTTPSListener(argument: clientpb_client_pb.HTTPListenerReq, callback: grpc.requestCallback<clientpb_client_pb.HTTPListener>): grpc.ClientUnaryCall;
  startHTTPSListener(argument: clientpb_client_pb.HTTPListenerReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.HTTPListener>): grpc.ClientUnaryCall;
  startHTTPSListener(argument: clientpb_client_pb.HTTPListenerReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.HTTPListener>): grpc.ClientUnaryCall;
  startHTTPListener(argument: clientpb_client_pb.HTTPListenerReq, callback: grpc.requestCallback<clientpb_client_pb.HTTPListener>): grpc.ClientUnaryCall;
  startHTTPListener(argument: clientpb_client_pb.HTTPListenerReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.HTTPListener>): grpc.ClientUnaryCall;
  startHTTPListener(argument: clientpb_client_pb.HTTPListenerReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.HTTPListener>): grpc.ClientUnaryCall;
  startTCPStagerListener(argument: clientpb_client_pb.StagerListenerReq, callback: grpc.requestCallback<clientpb_client_pb.StagerListener>): grpc.ClientUnaryCall;
  startTCPStagerListener(argument: clientpb_client_pb.StagerListenerReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.StagerListener>): grpc.ClientUnaryCall;
  startTCPStagerListener(argument: clientpb_client_pb.StagerListenerReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.StagerListener>): grpc.ClientUnaryCall;
  startHTTPStagerListener(argument: clientpb_client_pb.StagerListenerReq, callback: grpc.requestCallback<clientpb_client_pb.StagerListener>): grpc.ClientUnaryCall;
  startHTTPStagerListener(argument: clientpb_client_pb.StagerListenerReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.StagerListener>): grpc.ClientUnaryCall;
  startHTTPStagerListener(argument: clientpb_client_pb.StagerListenerReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.StagerListener>): grpc.ClientUnaryCall;
  lootAdd(argument: clientpb_client_pb.Loot, callback: grpc.requestCallback<clientpb_client_pb.Loot>): grpc.ClientUnaryCall;
  lootAdd(argument: clientpb_client_pb.Loot, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Loot>): grpc.ClientUnaryCall;
  lootAdd(argument: clientpb_client_pb.Loot, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Loot>): grpc.ClientUnaryCall;
  lootRm(argument: clientpb_client_pb.Loot, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  lootRm(argument: clientpb_client_pb.Loot, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  lootRm(argument: clientpb_client_pb.Loot, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  lootUpdate(argument: clientpb_client_pb.Loot, callback: grpc.requestCallback<clientpb_client_pb.Loot>): grpc.ClientUnaryCall;
  lootUpdate(argument: clientpb_client_pb.Loot, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Loot>): grpc.ClientUnaryCall;
  lootUpdate(argument: clientpb_client_pb.Loot, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Loot>): grpc.ClientUnaryCall;
  lootContent(argument: clientpb_client_pb.Loot, callback: grpc.requestCallback<clientpb_client_pb.Loot>): grpc.ClientUnaryCall;
  lootContent(argument: clientpb_client_pb.Loot, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Loot>): grpc.ClientUnaryCall;
  lootContent(argument: clientpb_client_pb.Loot, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Loot>): grpc.ClientUnaryCall;
  lootAll(argument: commonpb_common_pb.Empty, callback: grpc.requestCallback<clientpb_client_pb.AllLoot>): grpc.ClientUnaryCall;
  lootAll(argument: commonpb_common_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.AllLoot>): grpc.ClientUnaryCall;
  lootAll(argument: commonpb_common_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.AllLoot>): grpc.ClientUnaryCall;
  lootAllOf(argument: clientpb_client_pb.Loot, callback: grpc.requestCallback<clientpb_client_pb.AllLoot>): grpc.ClientUnaryCall;
  lootAllOf(argument: clientpb_client_pb.Loot, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.AllLoot>): grpc.ClientUnaryCall;
  lootAllOf(argument: clientpb_client_pb.Loot, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.AllLoot>): grpc.ClientUnaryCall;
  generate(argument: clientpb_client_pb.GenerateReq, callback: grpc.requestCallback<clientpb_client_pb.Generate>): grpc.ClientUnaryCall;
  generate(argument: clientpb_client_pb.GenerateReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Generate>): grpc.ClientUnaryCall;
  generate(argument: clientpb_client_pb.GenerateReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Generate>): grpc.ClientUnaryCall;
  regenerate(argument: clientpb_client_pb.RegenerateReq, callback: grpc.requestCallback<clientpb_client_pb.Generate>): grpc.ClientUnaryCall;
  regenerate(argument: clientpb_client_pb.RegenerateReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Generate>): grpc.ClientUnaryCall;
  regenerate(argument: clientpb_client_pb.RegenerateReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Generate>): grpc.ClientUnaryCall;
  implantBuilds(argument: commonpb_common_pb.Empty, callback: grpc.requestCallback<clientpb_client_pb.ImplantBuilds>): grpc.ClientUnaryCall;
  implantBuilds(argument: commonpb_common_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.ImplantBuilds>): grpc.ClientUnaryCall;
  implantBuilds(argument: commonpb_common_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.ImplantBuilds>): grpc.ClientUnaryCall;
  deleteImplantBuild(argument: clientpb_client_pb.DeleteReq, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  deleteImplantBuild(argument: clientpb_client_pb.DeleteReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  deleteImplantBuild(argument: clientpb_client_pb.DeleteReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  canaries(argument: commonpb_common_pb.Empty, callback: grpc.requestCallback<clientpb_client_pb.Canaries>): grpc.ClientUnaryCall;
  canaries(argument: commonpb_common_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Canaries>): grpc.ClientUnaryCall;
  canaries(argument: commonpb_common_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Canaries>): grpc.ClientUnaryCall;
  generateWGClientConfig(argument: commonpb_common_pb.Empty, callback: grpc.requestCallback<clientpb_client_pb.WGClientConfig>): grpc.ClientUnaryCall;
  generateWGClientConfig(argument: commonpb_common_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.WGClientConfig>): grpc.ClientUnaryCall;
  generateWGClientConfig(argument: commonpb_common_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.WGClientConfig>): grpc.ClientUnaryCall;
  generateUniqueIP(argument: commonpb_common_pb.Empty, callback: grpc.requestCallback<clientpb_client_pb.UniqueWGIP>): grpc.ClientUnaryCall;
  generateUniqueIP(argument: commonpb_common_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.UniqueWGIP>): grpc.ClientUnaryCall;
  generateUniqueIP(argument: commonpb_common_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.UniqueWGIP>): grpc.ClientUnaryCall;
  implantProfiles(argument: commonpb_common_pb.Empty, callback: grpc.requestCallback<clientpb_client_pb.ImplantProfiles>): grpc.ClientUnaryCall;
  implantProfiles(argument: commonpb_common_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.ImplantProfiles>): grpc.ClientUnaryCall;
  implantProfiles(argument: commonpb_common_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.ImplantProfiles>): grpc.ClientUnaryCall;
  deleteImplantProfile(argument: clientpb_client_pb.DeleteReq, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  deleteImplantProfile(argument: clientpb_client_pb.DeleteReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  deleteImplantProfile(argument: clientpb_client_pb.DeleteReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  saveImplantProfile(argument: clientpb_client_pb.ImplantProfile, callback: grpc.requestCallback<clientpb_client_pb.ImplantProfile>): grpc.ClientUnaryCall;
  saveImplantProfile(argument: clientpb_client_pb.ImplantProfile, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.ImplantProfile>): grpc.ClientUnaryCall;
  saveImplantProfile(argument: clientpb_client_pb.ImplantProfile, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.ImplantProfile>): grpc.ClientUnaryCall;
  msfStage(argument: clientpb_client_pb.MsfStagerReq, callback: grpc.requestCallback<clientpb_client_pb.MsfStager>): grpc.ClientUnaryCall;
  msfStage(argument: clientpb_client_pb.MsfStagerReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.MsfStager>): grpc.ClientUnaryCall;
  msfStage(argument: clientpb_client_pb.MsfStagerReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.MsfStager>): grpc.ClientUnaryCall;
  shellcodeRDI(argument: clientpb_client_pb.ShellcodeRDIReq, callback: grpc.requestCallback<clientpb_client_pb.ShellcodeRDI>): grpc.ClientUnaryCall;
  shellcodeRDI(argument: clientpb_client_pb.ShellcodeRDIReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.ShellcodeRDI>): grpc.ClientUnaryCall;
  shellcodeRDI(argument: clientpb_client_pb.ShellcodeRDIReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.ShellcodeRDI>): grpc.ClientUnaryCall;
  getCompiler(argument: commonpb_common_pb.Empty, callback: grpc.requestCallback<clientpb_client_pb.Compiler>): grpc.ClientUnaryCall;
  getCompiler(argument: commonpb_common_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Compiler>): grpc.ClientUnaryCall;
  getCompiler(argument: commonpb_common_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Compiler>): grpc.ClientUnaryCall;
  websites(argument: commonpb_common_pb.Empty, callback: grpc.requestCallback<clientpb_client_pb.Websites>): grpc.ClientUnaryCall;
  websites(argument: commonpb_common_pb.Empty, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Websites>): grpc.ClientUnaryCall;
  websites(argument: commonpb_common_pb.Empty, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Websites>): grpc.ClientUnaryCall;
  website(argument: clientpb_client_pb.Website, callback: grpc.requestCallback<clientpb_client_pb.Website>): grpc.ClientUnaryCall;
  website(argument: clientpb_client_pb.Website, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Website>): grpc.ClientUnaryCall;
  website(argument: clientpb_client_pb.Website, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Website>): grpc.ClientUnaryCall;
  websiteRemove(argument: clientpb_client_pb.Website, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  websiteRemove(argument: clientpb_client_pb.Website, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  websiteRemove(argument: clientpb_client_pb.Website, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  websiteAddContent(argument: clientpb_client_pb.WebsiteAddContent, callback: grpc.requestCallback<clientpb_client_pb.Website>): grpc.ClientUnaryCall;
  websiteAddContent(argument: clientpb_client_pb.WebsiteAddContent, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Website>): grpc.ClientUnaryCall;
  websiteAddContent(argument: clientpb_client_pb.WebsiteAddContent, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Website>): grpc.ClientUnaryCall;
  websiteUpdateContent(argument: clientpb_client_pb.WebsiteAddContent, callback: grpc.requestCallback<clientpb_client_pb.Website>): grpc.ClientUnaryCall;
  websiteUpdateContent(argument: clientpb_client_pb.WebsiteAddContent, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Website>): grpc.ClientUnaryCall;
  websiteUpdateContent(argument: clientpb_client_pb.WebsiteAddContent, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Website>): grpc.ClientUnaryCall;
  websiteRemoveContent(argument: clientpb_client_pb.WebsiteRemoveContent, callback: grpc.requestCallback<clientpb_client_pb.Website>): grpc.ClientUnaryCall;
  websiteRemoveContent(argument: clientpb_client_pb.WebsiteRemoveContent, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Website>): grpc.ClientUnaryCall;
  websiteRemoveContent(argument: clientpb_client_pb.WebsiteRemoveContent, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<clientpb_client_pb.Website>): grpc.ClientUnaryCall;
  ping(argument: sliverpb_sliver_pb.Ping, callback: grpc.requestCallback<sliverpb_sliver_pb.Ping>): grpc.ClientUnaryCall;
  ping(argument: sliverpb_sliver_pb.Ping, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Ping>): grpc.ClientUnaryCall;
  ping(argument: sliverpb_sliver_pb.Ping, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Ping>): grpc.ClientUnaryCall;
  ps(argument: sliverpb_sliver_pb.PsReq, callback: grpc.requestCallback<sliverpb_sliver_pb.Ps>): grpc.ClientUnaryCall;
  ps(argument: sliverpb_sliver_pb.PsReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Ps>): grpc.ClientUnaryCall;
  ps(argument: sliverpb_sliver_pb.PsReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Ps>): grpc.ClientUnaryCall;
  terminate(argument: sliverpb_sliver_pb.TerminateReq, callback: grpc.requestCallback<sliverpb_sliver_pb.Terminate>): grpc.ClientUnaryCall;
  terminate(argument: sliverpb_sliver_pb.TerminateReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Terminate>): grpc.ClientUnaryCall;
  terminate(argument: sliverpb_sliver_pb.TerminateReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Terminate>): grpc.ClientUnaryCall;
  ifconfig(argument: sliverpb_sliver_pb.IfconfigReq, callback: grpc.requestCallback<sliverpb_sliver_pb.Ifconfig>): grpc.ClientUnaryCall;
  ifconfig(argument: sliverpb_sliver_pb.IfconfigReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Ifconfig>): grpc.ClientUnaryCall;
  ifconfig(argument: sliverpb_sliver_pb.IfconfigReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Ifconfig>): grpc.ClientUnaryCall;
  netstat(argument: sliverpb_sliver_pb.NetstatReq, callback: grpc.requestCallback<sliverpb_sliver_pb.Netstat>): grpc.ClientUnaryCall;
  netstat(argument: sliverpb_sliver_pb.NetstatReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Netstat>): grpc.ClientUnaryCall;
  netstat(argument: sliverpb_sliver_pb.NetstatReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Netstat>): grpc.ClientUnaryCall;
  ls(argument: sliverpb_sliver_pb.LsReq, callback: grpc.requestCallback<sliverpb_sliver_pb.Ls>): grpc.ClientUnaryCall;
  ls(argument: sliverpb_sliver_pb.LsReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Ls>): grpc.ClientUnaryCall;
  ls(argument: sliverpb_sliver_pb.LsReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Ls>): grpc.ClientUnaryCall;
  cd(argument: sliverpb_sliver_pb.CdReq, callback: grpc.requestCallback<sliverpb_sliver_pb.Pwd>): grpc.ClientUnaryCall;
  cd(argument: sliverpb_sliver_pb.CdReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Pwd>): grpc.ClientUnaryCall;
  cd(argument: sliverpb_sliver_pb.CdReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Pwd>): grpc.ClientUnaryCall;
  pwd(argument: sliverpb_sliver_pb.PwdReq, callback: grpc.requestCallback<sliverpb_sliver_pb.Pwd>): grpc.ClientUnaryCall;
  pwd(argument: sliverpb_sliver_pb.PwdReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Pwd>): grpc.ClientUnaryCall;
  pwd(argument: sliverpb_sliver_pb.PwdReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Pwd>): grpc.ClientUnaryCall;
  rm(argument: sliverpb_sliver_pb.RmReq, callback: grpc.requestCallback<sliverpb_sliver_pb.Rm>): grpc.ClientUnaryCall;
  rm(argument: sliverpb_sliver_pb.RmReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Rm>): grpc.ClientUnaryCall;
  rm(argument: sliverpb_sliver_pb.RmReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Rm>): grpc.ClientUnaryCall;
  mkdir(argument: sliverpb_sliver_pb.MkdirReq, callback: grpc.requestCallback<sliverpb_sliver_pb.Mkdir>): grpc.ClientUnaryCall;
  mkdir(argument: sliverpb_sliver_pb.MkdirReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Mkdir>): grpc.ClientUnaryCall;
  mkdir(argument: sliverpb_sliver_pb.MkdirReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Mkdir>): grpc.ClientUnaryCall;
  download(argument: sliverpb_sliver_pb.DownloadReq, callback: grpc.requestCallback<sliverpb_sliver_pb.Download>): grpc.ClientUnaryCall;
  download(argument: sliverpb_sliver_pb.DownloadReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Download>): grpc.ClientUnaryCall;
  download(argument: sliverpb_sliver_pb.DownloadReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Download>): grpc.ClientUnaryCall;
  upload(argument: sliverpb_sliver_pb.UploadReq, callback: grpc.requestCallback<sliverpb_sliver_pb.Upload>): grpc.ClientUnaryCall;
  upload(argument: sliverpb_sliver_pb.UploadReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Upload>): grpc.ClientUnaryCall;
  upload(argument: sliverpb_sliver_pb.UploadReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Upload>): grpc.ClientUnaryCall;
  processDump(argument: sliverpb_sliver_pb.ProcessDumpReq, callback: grpc.requestCallback<sliverpb_sliver_pb.ProcessDump>): grpc.ClientUnaryCall;
  processDump(argument: sliverpb_sliver_pb.ProcessDumpReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.ProcessDump>): grpc.ClientUnaryCall;
  processDump(argument: sliverpb_sliver_pb.ProcessDumpReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.ProcessDump>): grpc.ClientUnaryCall;
  runAs(argument: sliverpb_sliver_pb.RunAsReq, callback: grpc.requestCallback<sliverpb_sliver_pb.RunAs>): grpc.ClientUnaryCall;
  runAs(argument: sliverpb_sliver_pb.RunAsReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.RunAs>): grpc.ClientUnaryCall;
  runAs(argument: sliverpb_sliver_pb.RunAsReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.RunAs>): grpc.ClientUnaryCall;
  impersonate(argument: sliverpb_sliver_pb.ImpersonateReq, callback: grpc.requestCallback<sliverpb_sliver_pb.Impersonate>): grpc.ClientUnaryCall;
  impersonate(argument: sliverpb_sliver_pb.ImpersonateReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Impersonate>): grpc.ClientUnaryCall;
  impersonate(argument: sliverpb_sliver_pb.ImpersonateReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Impersonate>): grpc.ClientUnaryCall;
  revToSelf(argument: sliverpb_sliver_pb.RevToSelfReq, callback: grpc.requestCallback<sliverpb_sliver_pb.RevToSelf>): grpc.ClientUnaryCall;
  revToSelf(argument: sliverpb_sliver_pb.RevToSelfReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.RevToSelf>): grpc.ClientUnaryCall;
  revToSelf(argument: sliverpb_sliver_pb.RevToSelfReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.RevToSelf>): grpc.ClientUnaryCall;
  getSystem(argument: clientpb_client_pb.GetSystemReq, callback: grpc.requestCallback<sliverpb_sliver_pb.GetSystem>): grpc.ClientUnaryCall;
  getSystem(argument: clientpb_client_pb.GetSystemReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.GetSystem>): grpc.ClientUnaryCall;
  getSystem(argument: clientpb_client_pb.GetSystemReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.GetSystem>): grpc.ClientUnaryCall;
  task(argument: sliverpb_sliver_pb.TaskReq, callback: grpc.requestCallback<sliverpb_sliver_pb.Task>): grpc.ClientUnaryCall;
  task(argument: sliverpb_sliver_pb.TaskReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Task>): grpc.ClientUnaryCall;
  task(argument: sliverpb_sliver_pb.TaskReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Task>): grpc.ClientUnaryCall;
  msf(argument: clientpb_client_pb.MSFReq, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  msf(argument: clientpb_client_pb.MSFReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  msf(argument: clientpb_client_pb.MSFReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  msfRemote(argument: clientpb_client_pb.MSFRemoteReq, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  msfRemote(argument: clientpb_client_pb.MSFRemoteReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  msfRemote(argument: clientpb_client_pb.MSFRemoteReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  executeAssembly(argument: sliverpb_sliver_pb.ExecuteAssemblyReq, callback: grpc.requestCallback<sliverpb_sliver_pb.ExecuteAssembly>): grpc.ClientUnaryCall;
  executeAssembly(argument: sliverpb_sliver_pb.ExecuteAssemblyReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.ExecuteAssembly>): grpc.ClientUnaryCall;
  executeAssembly(argument: sliverpb_sliver_pb.ExecuteAssemblyReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.ExecuteAssembly>): grpc.ClientUnaryCall;
  migrate(argument: clientpb_client_pb.MigrateReq, callback: grpc.requestCallback<sliverpb_sliver_pb.Migrate>): grpc.ClientUnaryCall;
  migrate(argument: clientpb_client_pb.MigrateReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Migrate>): grpc.ClientUnaryCall;
  migrate(argument: clientpb_client_pb.MigrateReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Migrate>): grpc.ClientUnaryCall;
  execute(argument: sliverpb_sliver_pb.ExecuteReq, callback: grpc.requestCallback<sliverpb_sliver_pb.Execute>): grpc.ClientUnaryCall;
  execute(argument: sliverpb_sliver_pb.ExecuteReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Execute>): grpc.ClientUnaryCall;
  execute(argument: sliverpb_sliver_pb.ExecuteReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Execute>): grpc.ClientUnaryCall;
  executeToken(argument: sliverpb_sliver_pb.ExecuteTokenReq, callback: grpc.requestCallback<sliverpb_sliver_pb.Execute>): grpc.ClientUnaryCall;
  executeToken(argument: sliverpb_sliver_pb.ExecuteTokenReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Execute>): grpc.ClientUnaryCall;
  executeToken(argument: sliverpb_sliver_pb.ExecuteTokenReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Execute>): grpc.ClientUnaryCall;
  sideload(argument: sliverpb_sliver_pb.SideloadReq, callback: grpc.requestCallback<sliverpb_sliver_pb.Sideload>): grpc.ClientUnaryCall;
  sideload(argument: sliverpb_sliver_pb.SideloadReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Sideload>): grpc.ClientUnaryCall;
  sideload(argument: sliverpb_sliver_pb.SideloadReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Sideload>): grpc.ClientUnaryCall;
  spawnDll(argument: sliverpb_sliver_pb.InvokeSpawnDllReq, callback: grpc.requestCallback<sliverpb_sliver_pb.SpawnDll>): grpc.ClientUnaryCall;
  spawnDll(argument: sliverpb_sliver_pb.InvokeSpawnDllReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.SpawnDll>): grpc.ClientUnaryCall;
  spawnDll(argument: sliverpb_sliver_pb.InvokeSpawnDllReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.SpawnDll>): grpc.ClientUnaryCall;
  screenshot(argument: sliverpb_sliver_pb.ScreenshotReq, callback: grpc.requestCallback<sliverpb_sliver_pb.Screenshot>): grpc.ClientUnaryCall;
  screenshot(argument: sliverpb_sliver_pb.ScreenshotReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Screenshot>): grpc.ClientUnaryCall;
  screenshot(argument: sliverpb_sliver_pb.ScreenshotReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Screenshot>): grpc.ClientUnaryCall;
  namedPipes(argument: sliverpb_sliver_pb.NamedPipesReq, callback: grpc.requestCallback<sliverpb_sliver_pb.NamedPipes>): grpc.ClientUnaryCall;
  namedPipes(argument: sliverpb_sliver_pb.NamedPipesReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.NamedPipes>): grpc.ClientUnaryCall;
  namedPipes(argument: sliverpb_sliver_pb.NamedPipesReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.NamedPipes>): grpc.ClientUnaryCall;
  tCPListener(argument: sliverpb_sliver_pb.TCPPivotReq, callback: grpc.requestCallback<sliverpb_sliver_pb.TCPPivot>): grpc.ClientUnaryCall;
  tCPListener(argument: sliverpb_sliver_pb.TCPPivotReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.TCPPivot>): grpc.ClientUnaryCall;
  tCPListener(argument: sliverpb_sliver_pb.TCPPivotReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.TCPPivot>): grpc.ClientUnaryCall;
  listPivots(argument: sliverpb_sliver_pb.PivotListReq, callback: grpc.requestCallback<sliverpb_sliver_pb.PivotList>): grpc.ClientUnaryCall;
  listPivots(argument: sliverpb_sliver_pb.PivotListReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.PivotList>): grpc.ClientUnaryCall;
  listPivots(argument: sliverpb_sliver_pb.PivotListReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.PivotList>): grpc.ClientUnaryCall;
  startService(argument: sliverpb_sliver_pb.StartServiceReq, callback: grpc.requestCallback<sliverpb_sliver_pb.ServiceInfo>): grpc.ClientUnaryCall;
  startService(argument: sliverpb_sliver_pb.StartServiceReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.ServiceInfo>): grpc.ClientUnaryCall;
  startService(argument: sliverpb_sliver_pb.StartServiceReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.ServiceInfo>): grpc.ClientUnaryCall;
  stopService(argument: sliverpb_sliver_pb.StopServiceReq, callback: grpc.requestCallback<sliverpb_sliver_pb.ServiceInfo>): grpc.ClientUnaryCall;
  stopService(argument: sliverpb_sliver_pb.StopServiceReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.ServiceInfo>): grpc.ClientUnaryCall;
  stopService(argument: sliverpb_sliver_pb.StopServiceReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.ServiceInfo>): grpc.ClientUnaryCall;
  removeService(argument: sliverpb_sliver_pb.RemoveServiceReq, callback: grpc.requestCallback<sliverpb_sliver_pb.ServiceInfo>): grpc.ClientUnaryCall;
  removeService(argument: sliverpb_sliver_pb.RemoveServiceReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.ServiceInfo>): grpc.ClientUnaryCall;
  removeService(argument: sliverpb_sliver_pb.RemoveServiceReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.ServiceInfo>): grpc.ClientUnaryCall;
  makeToken(argument: sliverpb_sliver_pb.MakeTokenReq, callback: grpc.requestCallback<sliverpb_sliver_pb.MakeToken>): grpc.ClientUnaryCall;
  makeToken(argument: sliverpb_sliver_pb.MakeTokenReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.MakeToken>): grpc.ClientUnaryCall;
  makeToken(argument: sliverpb_sliver_pb.MakeTokenReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.MakeToken>): grpc.ClientUnaryCall;
  getEnv(argument: sliverpb_sliver_pb.EnvReq, callback: grpc.requestCallback<sliverpb_sliver_pb.EnvInfo>): grpc.ClientUnaryCall;
  getEnv(argument: sliverpb_sliver_pb.EnvReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.EnvInfo>): grpc.ClientUnaryCall;
  getEnv(argument: sliverpb_sliver_pb.EnvReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.EnvInfo>): grpc.ClientUnaryCall;
  setEnv(argument: sliverpb_sliver_pb.SetEnvReq, callback: grpc.requestCallback<sliverpb_sliver_pb.SetEnv>): grpc.ClientUnaryCall;
  setEnv(argument: sliverpb_sliver_pb.SetEnvReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.SetEnv>): grpc.ClientUnaryCall;
  setEnv(argument: sliverpb_sliver_pb.SetEnvReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.SetEnv>): grpc.ClientUnaryCall;
  unsetEnv(argument: sliverpb_sliver_pb.UnsetEnvReq, callback: grpc.requestCallback<sliverpb_sliver_pb.UnsetEnv>): grpc.ClientUnaryCall;
  unsetEnv(argument: sliverpb_sliver_pb.UnsetEnvReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.UnsetEnv>): grpc.ClientUnaryCall;
  unsetEnv(argument: sliverpb_sliver_pb.UnsetEnvReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.UnsetEnv>): grpc.ClientUnaryCall;
  backdoor(argument: sliverpb_sliver_pb.BackdoorReq, callback: grpc.requestCallback<sliverpb_sliver_pb.Backdoor>): grpc.ClientUnaryCall;
  backdoor(argument: sliverpb_sliver_pb.BackdoorReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Backdoor>): grpc.ClientUnaryCall;
  backdoor(argument: sliverpb_sliver_pb.BackdoorReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Backdoor>): grpc.ClientUnaryCall;
  registryRead(argument: sliverpb_sliver_pb.RegistryReadReq, callback: grpc.requestCallback<sliverpb_sliver_pb.RegistryRead>): grpc.ClientUnaryCall;
  registryRead(argument: sliverpb_sliver_pb.RegistryReadReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.RegistryRead>): grpc.ClientUnaryCall;
  registryRead(argument: sliverpb_sliver_pb.RegistryReadReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.RegistryRead>): grpc.ClientUnaryCall;
  registryWrite(argument: sliverpb_sliver_pb.RegistryWriteReq, callback: grpc.requestCallback<sliverpb_sliver_pb.RegistryWrite>): grpc.ClientUnaryCall;
  registryWrite(argument: sliverpb_sliver_pb.RegistryWriteReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.RegistryWrite>): grpc.ClientUnaryCall;
  registryWrite(argument: sliverpb_sliver_pb.RegistryWriteReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.RegistryWrite>): grpc.ClientUnaryCall;
  registryCreateKey(argument: sliverpb_sliver_pb.RegistryCreateKeyReq, callback: grpc.requestCallback<sliverpb_sliver_pb.RegistryCreateKey>): grpc.ClientUnaryCall;
  registryCreateKey(argument: sliverpb_sliver_pb.RegistryCreateKeyReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.RegistryCreateKey>): grpc.ClientUnaryCall;
  registryCreateKey(argument: sliverpb_sliver_pb.RegistryCreateKeyReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.RegistryCreateKey>): grpc.ClientUnaryCall;
  runSSHCommand(argument: sliverpb_sliver_pb.SSHCommandReq, callback: grpc.requestCallback<sliverpb_sliver_pb.SSHCommand>): grpc.ClientUnaryCall;
  runSSHCommand(argument: sliverpb_sliver_pb.SSHCommandReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.SSHCommand>): grpc.ClientUnaryCall;
  runSSHCommand(argument: sliverpb_sliver_pb.SSHCommandReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.SSHCommand>): grpc.ClientUnaryCall;
  wGStartPortForward(argument: sliverpb_sliver_pb.WGPortForwardStartReq, callback: grpc.requestCallback<sliverpb_sliver_pb.WGPortForward>): grpc.ClientUnaryCall;
  wGStartPortForward(argument: sliverpb_sliver_pb.WGPortForwardStartReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.WGPortForward>): grpc.ClientUnaryCall;
  wGStartPortForward(argument: sliverpb_sliver_pb.WGPortForwardStartReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.WGPortForward>): grpc.ClientUnaryCall;
  wGStopPortForward(argument: sliverpb_sliver_pb.WGPortForwardStopReq, callback: grpc.requestCallback<sliverpb_sliver_pb.WGPortForward>): grpc.ClientUnaryCall;
  wGStopPortForward(argument: sliverpb_sliver_pb.WGPortForwardStopReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.WGPortForward>): grpc.ClientUnaryCall;
  wGStopPortForward(argument: sliverpb_sliver_pb.WGPortForwardStopReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.WGPortForward>): grpc.ClientUnaryCall;
  wGStartSocks(argument: sliverpb_sliver_pb.WGSocksStartReq, callback: grpc.requestCallback<sliverpb_sliver_pb.WGSocks>): grpc.ClientUnaryCall;
  wGStartSocks(argument: sliverpb_sliver_pb.WGSocksStartReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.WGSocks>): grpc.ClientUnaryCall;
  wGStartSocks(argument: sliverpb_sliver_pb.WGSocksStartReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.WGSocks>): grpc.ClientUnaryCall;
  wGStopSocks(argument: sliverpb_sliver_pb.WGSocksStopReq, callback: grpc.requestCallback<sliverpb_sliver_pb.WGSocks>): grpc.ClientUnaryCall;
  wGStopSocks(argument: sliverpb_sliver_pb.WGSocksStopReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.WGSocks>): grpc.ClientUnaryCall;
  wGStopSocks(argument: sliverpb_sliver_pb.WGSocksStopReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.WGSocks>): grpc.ClientUnaryCall;
  wGListForwarders(argument: sliverpb_sliver_pb.WGTCPForwardersReq, callback: grpc.requestCallback<sliverpb_sliver_pb.WGTCPForwarders>): grpc.ClientUnaryCall;
  wGListForwarders(argument: sliverpb_sliver_pb.WGTCPForwardersReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.WGTCPForwarders>): grpc.ClientUnaryCall;
  wGListForwarders(argument: sliverpb_sliver_pb.WGTCPForwardersReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.WGTCPForwarders>): grpc.ClientUnaryCall;
  wGListSocksServers(argument: sliverpb_sliver_pb.WGSocksServersReq, callback: grpc.requestCallback<sliverpb_sliver_pb.WGSocksServers>): grpc.ClientUnaryCall;
  wGListSocksServers(argument: sliverpb_sliver_pb.WGSocksServersReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.WGSocksServers>): grpc.ClientUnaryCall;
  wGListSocksServers(argument: sliverpb_sliver_pb.WGSocksServersReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.WGSocksServers>): grpc.ClientUnaryCall;
  shell(argument: sliverpb_sliver_pb.ShellReq, callback: grpc.requestCallback<sliverpb_sliver_pb.Shell>): grpc.ClientUnaryCall;
  shell(argument: sliverpb_sliver_pb.ShellReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Shell>): grpc.ClientUnaryCall;
  shell(argument: sliverpb_sliver_pb.ShellReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Shell>): grpc.ClientUnaryCall;
  portfwd(argument: sliverpb_sliver_pb.PortfwdReq, callback: grpc.requestCallback<sliverpb_sliver_pb.Portfwd>): grpc.ClientUnaryCall;
  portfwd(argument: sliverpb_sliver_pb.PortfwdReq, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Portfwd>): grpc.ClientUnaryCall;
  portfwd(argument: sliverpb_sliver_pb.PortfwdReq, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Portfwd>): grpc.ClientUnaryCall;
  createTunnel(argument: sliverpb_sliver_pb.Tunnel, callback: grpc.requestCallback<sliverpb_sliver_pb.Tunnel>): grpc.ClientUnaryCall;
  createTunnel(argument: sliverpb_sliver_pb.Tunnel, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Tunnel>): grpc.ClientUnaryCall;
  createTunnel(argument: sliverpb_sliver_pb.Tunnel, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<sliverpb_sliver_pb.Tunnel>): grpc.ClientUnaryCall;
  closeTunnel(argument: sliverpb_sliver_pb.Tunnel, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  closeTunnel(argument: sliverpb_sliver_pb.Tunnel, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  closeTunnel(argument: sliverpb_sliver_pb.Tunnel, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<commonpb_common_pb.Empty>): grpc.ClientUnaryCall;
  tunnelData(metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientDuplexStream<sliverpb_sliver_pb.TunnelData, sliverpb_sliver_pb.TunnelData>;
  tunnelData(metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientDuplexStream<sliverpb_sliver_pb.TunnelData, sliverpb_sliver_pb.TunnelData>;
  events(argument: commonpb_common_pb.Empty, metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientReadableStream<clientpb_client_pb.Event>;
  events(argument: commonpb_common_pb.Empty, metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientReadableStream<clientpb_client_pb.Event>;
}
